name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Workflow akan dijalankan saat ada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Google Cloud credentials
      run: |
        echo "${{ secrets.CREDENTIALS }}" > credentials.json

    - name: Run Streamlit App
      run: |
        streamlit run sireki.py
